# Generated by Django 5.2.10 on 2026-02-10 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_size', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_game_over', models.BooleanField(default=False)),
                ('current_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_current_turn', to=settings.AUTH_USER_MODEL)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_player_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('x', 'y'), name='unique_board_position')],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_start', to='game.position')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_end', to='game.position')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='end_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_end_1', to='game.position'),
        ),
        migrations.AddField(
            model_name='game',
            name='end_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_end_2', to='game.position'),
        ),
    ]
